
(function(){
  if(window.__sqFix95MissX3ConsolidatedTimed)return;
  window.__sqFix95MissX3ConsolidatedTimed=true;
  window.__sqMissX3CanonicalVisualOnly=true;
  var DMD_STEP_MS=75,DMD_HOLD_AFTER_MS=105,BUSY_EXTRA_MS=150;
  function getGameState(){try{if(typeof state!=='undefined'&&state)return state;}catch(_){}try{if(window.state)return window.state;}catch(_){}return null;}
  function sig(){try{var st=getGameState();if(!st)return'';return[st.currentRound,st.currentPlayer,st.currentDart,JSON.stringify(st.score||[]).length].join('|');}catch(_){return'';}}
  function remainingMisses(){try{var st=getGameState();var d=Number(st&&st.currentDart||0);return Math.max(1,Math.min(3,3-d));}catch(_){return 3;}}
  function isMissX3Target(target){try{var el=target&&target.closest?target.closest('.dtX3, button'):null;if(!el)return null;if(el.classList&&el.classList.contains('dtX3'))return el;var txt=String(el.textContent||el.innerText||el.getAttribute('aria-label')||el.title||'').toUpperCase().replace(/\s+/g,'').replace('×','X');return(txt==='MISSX3'||txt==='MISSX2'||txt==='MISSX1'||txt==='MISS3'||txt.indexOf('MISSX')===0)?el:null;}catch(_){return null;}}
  function dartToken(d,round){try{var k=String(d&&d.kind||d&&d.type||'').trim();var pts=Number(d&&(d.points??d.pts??d.score) || 0);if(/^Miss$/i.test(k)||pts===0)return'X';if(/^B$/i.test(k)||(d&&d.bull))return'B';if(round&&round.type==='number'){var target=Number(round.target||0);if(target>0){if(pts===target*3)return'T';if(pts===target*2)return'D';if(pts===target)return'S';}}if(round&&round.type==='doubles')return'D';if(round&&round.type==='triples')return'T';if(round&&round.type==='bull')return'B';if(/^(Triple|T)$/i.test(k))return'T';if(/^(Double|D)$/i.test(k))return'D';if(/^(Single|S)$/i.test(k))return'S';return(k||' ').slice(0,1).toUpperCase();}catch(_){return' ';}}
  function currentVisitSnapshot(){var cells=[' ',' ',' '],start=0;try{var st=getGameState();if(!st)return{cells:cells,start:start};start=Math.max(0,Math.min(2,Number(st.currentDart||0)));var p=Number(st.currentPlayer||0),r=Number(st.currentRound||0);var entry=st.score&&st.score[p]&&st.score[p][r];var darts=entry&&Array.isArray(entry.darts)?entry.darts:[];var round=(Array.isArray(st.rounds)&&st.rounds[r])||(typeof ROUNDS!=='undefined'&&ROUNDS[r])||null;for(var i=0;i<Math.min(start,3,darts.length);i++)if(darts[i])cells[i]=dartToken(darts[i],round);}catch(_){}return{cells:cells,start:start};}
  function lowerRowFor(step,snap){var cells=(snap&&Array.isArray(snap.cells)?snap.cells:[' ',' ',' ']).slice(0,3);while(cells.length<3)cells.push(' ');var start=Math.max(0,Math.min(2,Number(snap&&snap.start||0)));for(var i=0;i<step&&start+i<3;i++)cells[start+i]='X';return cells[0]+' / '+cells[1]+' / '+cells[2];}
  function showDmdStep(i,snap){try{var payload={z2:'Miss',z3:lowerRowFor(i,snap),z3Small:true};var opts={type:'snap',ms:125,revealMs:90,amp:2.8,fx:'impact'};if(window.sqDmdShowZones)window.sqDmdShowZones(payload,opts);else if(typeof sqDmdShowZones==='function')sqDmdShowZones(payload,opts);}catch(_){}}
  function playMissDmdSequence(n){n=Math.max(1,Math.min(3,Number(n||3)));var snap=currentVisitSnapshot();try{window.__sqDmdHardClearQueue&&window.__sqDmdHardClearQueue();}catch(_){}try{window.__sqSuppressMissCallouts=true;window.__sqDmdBulkMiss=true;}catch(_){}for(var i=1;i<=n;i++){(function(step){setTimeout(function(){showDmdStep(step,snap);},(step-1)*DMD_STEP_MS);})(i);}return(n*DMD_STEP_MS)+DMD_HOLD_AFTER_MS;}
  function flashButton(btn){try{if(!btn)return;btn.classList.remove('sq-missx3-hit95');void btn.offsetWidth;btn.classList.add('sq-missx3-hit95');var r=btn.getBoundingClientRect();if(r.width>0&&r.height>0){var ghost=document.createElement('div');ghost.className='sq-missx3-ghost95';ghost.style.left=r.left+'px';ghost.style.top=r.top+'px';ghost.style.width=r.width+'px';ghost.style.height=r.height+'px';try{ghost.style.borderRadius=(getComputedStyle(btn).borderRadius||'14px');}catch(_){ghost.style.borderRadius='14px';}document.body.appendChild(ghost);setTimeout(function(){try{ghost.remove();}catch(_){}},340);}setTimeout(function(){try{btn.classList.remove('sq-missx3-hit95');}catch(_){}},390);}catch(_){}}
  function recordMissesSilently(n){var st=getGameState();if(!st||st.finished||st.gameAwarded)return 0;n=Math.max(1,Math.min(3,Number(n||remainingMisses())));var done=0;try{window.__sqDmdBulkMiss=true;window.__sqSuppressMissCallouts=true;}catch(_){}for(var i=0;i<n;i++){try{st=getGameState();if(!st||st.finished||st.gameAwarded)break;if(Number(st.currentDart||0)>=3)break;if(typeof recordThrow==='function'){recordThrow({kind:'Miss'});done++;}else if(typeof window.recordThrow==='function'){window.recordThrow({kind:'Miss'});done++;}else break;}catch(err){try{console.warn('[SQ] Fix95 MISS x3 record failed',err);}catch(_){}break;}}try{if(typeof updateUI==='function')updateUI();}catch(_){}try{if(typeof save==='function')save();}catch(_){}return done;}
  window.__sqForceMissN=function(n){return recordMissesSilently(n);};
  window.__sqMissX3Debug=function(){var st=getGameState();return{hasState:!!st,currentRound:st&&st.currentRound,currentPlayer:st&&st.currentPlayer,currentDart:st&&st.currentDart,busyUntil:window.__sqMissX3BusyUntil||0,hasRecordThrow:(typeof recordThrow==='function')||(typeof window.recordThrow==='function'),buttons:Array.from(document.querySelectorAll('.dtX3')).map(function(b){var r=b.getBoundingClientRect();return{text:b.textContent,rect:{x:r.x,y:r.y,w:r.width,h:r.height}};})};};
  function handleMissX3(e){var btn=isMissX3Target(e.target);if(!btn)return;var now=Date.now();try{e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();}catch(_){}if(now<Number(window.__sqMissX3BusyUntil||0))return;var n=remainingMisses();var before=sig();flashButton(btn);var delay=playMissDmdSequence(n);window.__sqMissX3BusyUntil=now+delay+BUSY_EXTRA_MS;setTimeout(function(){try{var done=recordMissesSilently(n);if(!done||sig()===before)recordMissesSilently(n);}catch(_){}setTimeout(function(){try{window.__sqDmdBulkMiss=false;window.__sqSuppressMissCallouts=false;}catch(_){}},260);},delay);}
  ['pointerdown','touchstart','click'].forEach(function(type){document.addEventListener(type,handleMissX3,true);});
  try{console.info('[SQ] Fix96 MISS xN punch sequence active');}catch(_){}
})();
