
(function(){
 if(window.__sqFix77TurboRefine)return; window.__sqFix77TurboRefine=true;
 function isTurbo(){try{const m=state?.match||{},d=window.__sqTournamentDraft||state?.__sqTournamentDraft||null,t=String(m.tournamentType||m.type||d?.type||state?.tournamentType||'').toLowerCase();return !!(t==='turbo'||m.strictTimer===true||m.throwLimitSeconds===20||state?.strictTimer===true||state?.throwLimitSeconds===20)}catch(_){return false}}
 function startIdx(){try{const r=state?.match?.tournamentRules||state?.__sqTournamentDraft?.rules||window.__sqTournamentDraft?.rules||{};const n=Number(r.startRoundIndex??7);return Number.isFinite(n)?Math.max(0,n):7}catch(_){return 7}}
 window.__sqIsTurboTournamentGame=isTurbo;
 function pathFor(w,h,r){const x=4,y=4,W=Math.max(10,w-8),H=Math.max(10,h-8),rr=Math.max(8,Math.min(r,W/2,H/2)),cx=x+W/2;return 'M '+cx+' '+y+' H '+(x+W-rr)+' Q '+(x+W)+' '+y+' '+(x+W)+' '+(y+rr)+' V '+(y+H-rr)+' Q '+(x+W)+' '+(y+H)+' '+(x+W-rr)+' '+(y+H)+' H '+(x+rr)+' Q '+x+' '+(y+H)+' '+x+' '+(y+H-rr)+' V '+(y+rr)+' Q '+x+' '+y+' '+(x+rr)+' '+y+' H '+cx}
 function ensureSvg(box){if(!box)return null;let svg=box.querySelector(':scope > svg.sqTurboSvg');if(!svg){svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('sqTurboSvg');svg.setAttribute('preserveAspectRatio','none');const b=document.createElementNS('http://www.w3.org/2000/svg','path');b.classList.add('sqTurboBase');const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.classList.add('sqTurboProgress');svg.append(b,p);box.appendChild(svg)}return svg}
 function drawSvg(box,pct){try{if(!box||!isTurbo())return;const svg=ensureSvg(box),rect=box.getBoundingClientRect(),w=Math.max(40,rect.width+16),h=Math.max(30,rect.height+16);svg.setAttribute('viewBox','0 0 '+w+' '+h);const d=pathFor(w,h,24),base=svg.querySelector('.sqTurboBase'),prog=svg.querySelector('.sqTurboProgress');base.setAttribute('d',d);prog.setAttribute('d',d);const len=prog.getTotalLength?prog.getTotalLength():(2*w+2*h);prog.style.strokeDasharray=String(len);prog.style.strokeDashoffset=String(len*(1-Math.max(0,Math.min(1,pct))))}catch(_){}}
 function activeBox(){try{return document.querySelector('.livev2panel .v2ScoreBox[data-p="'+Number(state?.currentPlayer||0)+'"]')}catch(_){return null}}
 function tick(){try{document.querySelectorAll('.livev2panel .v2ScoreBox:not(.sqTurboTimerActive)>svg.sqTurboSvg').forEach(x=>x.remove());const st=window.__sqTurboTimerStatus?window.__sqTurboTimerStatus():null;if(st&&st.active&&st.timer&&Number.isFinite(st.timer.elapsedMs))drawSvg(activeBox(),Math.min(1,st.timer.elapsedMs/20000))}catch(_){} requestAnimationFrame(tick)}
 requestAnimationFrame(tick);
 function blankPreRows(){try{if(!isTurbo())return;const rows=document.getElementById('v2Rows');if(!rows)return;const pCount=Array.isArray(state?.players)?state.players.length:2,cutoff=startIdx(),kids=Array.from(rows.children);for(let i=0;i<kids.length;i++){const badge=kids[i];if(!badge.classList||!badge.classList.contains('v2Badge'))continue;const n=Number(String(badge.textContent||'').trim()),idx=Number.isFinite(n)?(n-10):-1;if(idx>=0&&idx<cutoff){for(let j=1;j<=pCount;j++){const cell=kids[i+j];if(cell&&cell.classList&&cell.classList.contains('v2Cell')){cell.classList.add('sqTurboPreStartCell');cell.querySelectorAll('.v2CellNum,.v2SoloScore').forEach(el=>{el.textContent=''})}}}}}catch(_){}}
 const old=window.updateUI||(typeof updateUI==='function'?updateUI:null);if(old&&!old.__sqFix77Wrapped){const wrapped=function(){const ret=old.apply(this,arguments);setTimeout(blankPreRows,0);return ret};wrapped.__sqFix77Wrapped=true;window.updateUI=wrapped;try{updateUI=wrapped}catch(_){}}
 setInterval(blankPreRows,300);
})();
