
(function(){
  if(window.__sqFix90TournamentUiThrowOrderMiss)return;
  window.__sqFix90TournamentUiThrowOrderMiss=true;
  function isTournamentState(){try{return!!(window.state&&state.match&&(state.match.tournament||state.match.tournamentType||state.__sqTournamentDraft||window.__sqTournamentDraft));}catch(_){return false;}}
  function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
  function playerFor(seedPlayer){const name=String(seedPlayer&&seedPlayer.name||'').trim();const raw=seedPlayer&&seedPlayer.raw?seedPlayer.raw:{};let parts={first:name,last:''};try{if(typeof __sqNameParts==='function')parts=__sqNameParts(name);}catch(_){}let init=name.slice(0,2).toUpperCase();try{if(typeof __sqNormalizeInitials==='function')init=__sqNormalizeInitials(raw.initials,name);}catch(_){}return{type:raw.type||'registered',id:raw.id||null,name,first_name:raw.first_name||raw.first||parts.first||name,last_name:raw.last_name||raw.last||parts.last||'',nickname:raw.nickname||'',initials:init,color:null,tournamentSeed:seedPlayer&&seedPlayer.seed||null};}
  function treeHtml(draft){const bracket=Array.isArray(draft&&draft.bracket)?draft.bracket:[];const title=String((draft&&draft.type)||'').toUpperCase()+' / '+String((draft&&draft.size)||'')+' PLAYERS';const rows=bracket.map(m=>'<div class="sg-bracket-match"><div class="sg-bracket-team"><span class="sg-bracket-seed">#'+esc(m.a&&m.a.seed)+'</span>'+esc(m.a&&m.a.name)+'</div><div class="sg-bracket-vs">VS</div><div class="sg-bracket-team"><span class="sg-bracket-seed">#'+esc(m.b&&m.b.seed)+'</span>'+esc(m.b&&m.b.name)+'</div></div>').join('');return'<div class="sg-tournament-bracket"><div class="sg-tournament-bracket-title">'+esc(title)+'</div><div class="sg-bracket-round">'+rows+'</div></div>';}
  function startTournamentFromDraft(draft){try{const first=draft&&Array.isArray(draft.bracket)&&draft.bracket[0];if(!first||!first.a||!first.b){try{toast('Tournament draft is not ready.');}catch(_){}return;}window.__sqSelectedMode='official';state.players=[playerFor(first.a),playerFor(first.b)];try{assignUniqueColors(state.players);}catch(_){}const matchId=(typeof genUuidV4==='function')?genUuidV4():('tournament-'+Date.now());const roundName=draft.size===8?'Quarter-final':'Semi-final';state.match={id:matchId,mode:'official',tournament:true,tournamentType:draft.type,tournamentSize:draft.size,tournamentRound:roundName,tournamentMatch:first.match||1,tournamentRules:draft.rules||{},forcePractice:false,practiceType:null,createdAtIso:new Date().toISOString(),targetWins:1,gameNumber:1,wins:Array.from({length:2},()=>0),history:[],completedLogged:false};state.__sqTournamentDraft=draft;state.__sqTournamentActive={tournamentId:matchId,type:draft.type,size:draft.size,currentMatch:first.match||1,currentRound:roundName,bracket:draft.bracket};state.matchAgg=null;try{ensureMatchAgg();}catch(_){}try{document.querySelectorAll('.modal-backdrop').forEach(x=>x.remove());}catch(_){}try{startNewGame(false);}catch(e){console.error('[SQ] Tournament restart from tree failed',e);}try{save();}catch(_){}}catch(e){console.error('[SQ] Tournament start from draft failed',e);}}
  window.__sqReopenTournamentTreeFromDraft=function(){const draft=window.__sqTournamentDraft||(window.state&&state.__sqTournamentDraft);if(!draft){try{toast('Tournament draft not found.');}catch(_){}return;}const ov=document.createElement('div');ov.className='modal-backdrop';const md=document.createElement('div');md.className='modal';md.style.maxWidth='760px';const h=document.createElement('h3');h.textContent='Tournament Tree';const body=document.createElement('div');body.className='modal-body';body.innerHTML='<div class="sg-tournament-intro"><div class="sg-tournament-title">RANDOMISED KNOCKOUT TREE</div></div>'+treeHtml(draft);const ft=document.createElement('div');ft.className='modal-footer sg-tournament-start-footer';const start=document.createElement('button');start.className='btn primary';start.textContent='START TOURNAMENT';start.onclick=()=>startTournamentFromDraft(draft);const back=document.createElement('button');back.className='btn';back.textContent='Back';back.onclick=()=>ov.remove();ft.append(start,back);md.append(h,body,ft);ov.appendChild(md);document.body.appendChild(ov);md.tabIndex=0;md.focus();};
  try{if(typeof showPlayerOrderDialog==='function'&&!showPlayerOrderDialog.__sqFix90BackWrapped){const orig=showPlayerOrderDialog;showPlayerOrderDialog=function(){const ret=orig.apply(this,arguments);setTimeout(function(){try{if(!isTournamentState())return;document.querySelectorAll('.modal-throworder .to-back').forEach(function(btn){if(btn.__sqFix90Bound)return;btn.__sqFix90Bound=true;btn.onclick=function(e){e.preventDefault();e.stopPropagation();try{const ov=btn.closest('.modal-backdrop');if(ov)ov.remove();}catch(_){}window.__sqReopenTournamentTreeFromDraft();};});}catch(_){ }},0);return ret;};showPlayerOrderDialog.__sqFix90BackWrapped=true;}}catch(e){console.warn('[SQ] Fix90 throw-order Back patch failed',e);}
  function remainingMisses(){try{return Math.max(1,Math.min(3,3-Number(state&&state.currentDart||0)));}catch(_){return 3;}}
  function forceMiss(n){n=Math.max(1,Math.min(3,Number(n||remainingMisses())));try{window.__sqDmdBulkMiss=true;}catch(_){}for(let i=0;i<n;i++){try{if(!window.state||state.finished||state.gameAwarded)break;if(Number(state.currentDart||0)>=3)break;if(typeof recordThrow==='function')recordThrow({kind:'Miss'});else if(typeof window.recordThrow==='function')window.recordThrow({kind:'Miss'});}catch(e){console.warn('[SQ] Fix90 force MISS failed',e);break;}}setTimeout(()=>{try{window.__sqDmdBulkMiss=false;updateUI();save();}catch(_){}},60);}
  window.__sqForceMissN=forceMiss;let lastMissAt=0;
  function isMissXTarget(t){try{const el=t&&t.closest?t.closest('.dtX3,button'):null;if(!el)return null;if(el.classList&&el.classList.contains('dtX3'))return el;const txt=String(el.textContent||el.innerText||'').toUpperCase().replace(/\s+/g,'');return(txt.indexOf('MISSX')===0||txt==='MISSX3'||txt==='MISS3')?el:null;}catch(_){return null;}}
  function hardMissHandler(e){return;}
  ['pointerup','touchend','click'].forEach(type=>document.addEventListener(type,hardMissHandler,true));
  try{console.info('[SQ] Fix90 tournament UI / throw-order back / MISS x3 active');}catch(_){}
})();
