
(function(){
  if(window.__sqFix83TournamentLeaderboardBracket)return; window.__sqFix83TournamentLeaderboardBracket=true;
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]);});}
  function txt(el){return String(el&&el.textContent||'').replace(/\s+/g,' ').trim().toUpperCase();}
  function isLeaderboard(){return document.body&&document.body.dataset&&document.body.dataset.page==='leaderboard'&&document.getElementById('leaderboard');}
  function isTournament(){try{const m=window.state&&state.match?state.match:{}; if(m.tournament||m.tournamentType||m.tournamentSize||m.tournamentMatch)return true; if(state&& (state.__sqTournamentActive||state.__sqTournamentDraft))return true; if(window.__sqTournamentDraft)return true; const ss=sessionStorage.getItem('sq_tournament_runtime_v1'); if(ss)return true;}catch(_){} return false;}
  function matchDone(){try{const w=Array.isArray(state?.match?.wins)?state.match.wins:[],t=Number(state?.match?.targetWins||1);return !!(w.length&&Math.max.apply(null,w)>=t)}catch(_){return false}}
  function playerName(p){return String(p&&p.name||p&&p.player||'TBC').trim()||'TBC';}
  function seedLabel(p){return p&&p.seed!=null?'#'+p.seed:(p&&p.tournamentSeed!=null?'#'+p.tournamentSeed:'');}
  function active(){try{state.__sqTournamentActive=state.__sqTournamentActive||{};return state.__sqTournamentActive}catch(_){return {}}}
  function draft(){try{return state?.__sqTournamentDraft||window.__sqTournamentDraft||active()||{}}catch(_){return {}}}
  function currentWinner(){try{const players=Array.isArray(state?.players)?state.players:[]; const totals=(Array.isArray(state?.match?.history)&&state.match.history.length&&Array.isArray(state.match.history[state.match.history.length-1]?.totals))?state.match.history[state.match.history.length-1].totals:players.map((_,i)=>typeof totalScoreForPlayer==='function'?totalScoreForPlayer(i):0); let wi=0,max=-Infinity; totals.forEach((v,i)=>{const n=Number(v||0); if(n>max){max=n;wi=i}}); const p=players[wi]; return p?{seed:Number(p.tournamentSeed||p.seed||0)||null,name:playerName(p),raw:p,total:max}:null;}catch(_){return null}}
  function captureResult(){try{const a=active(),m=state?.match||{}; a.results=a.results||{}; const no=Number(m.tournamentMatch||a.currentMatch||1); if(!a.results[no]){const w=currentWinner(); if(w&&w.name)a.results[no]=Object.assign({match:no,completedAt:new Date().toISOString()},w);} state.__sqTournamentActive=a; try{save()}catch(_){}}catch(e){console.warn('[SQ] Fix83 capture failed',e)}}
  function seedMap(){const mp=new Map();try{(active().players||draft().players||[]).forEach(p=>{if(p&&p.seed!=null)mp.set(Number(p.seed),p);});(active().bracket||draft().bracket||[]).forEach(m=>[m.a,m.b].forEach(p=>{if(p&&p.seed!=null&&!mp.has(Number(p.seed)))mp.set(Number(p.seed),p)}));}catch(_){} return mp;}
  function resultPlayer(matchNo){try{const r=active().results&&active().results[matchNo]; if(!r)return null; const p=seedMap().get(Number(r.seed||r.winnerSeed)); return p||{seed:r.seed||r.winnerSeed,name:r.name||r.winnerName};}catch(_){return null}}
  function initialMatch(no){try{return (active().bracket||draft().bracket||[]).find(m=>Number(m.match)===Number(no))||null}catch(_){return null}}
  function matchDef(no){const size=Number(active().size||draft().size||state?.match?.tournamentSize||4); const init=initialMatch(no); if(init)return init; if(size===4&&no===3)return{match:3,round:'Final',a:resultPlayer(1),b:resultPlayer(2)}; if(size===8){if(no===5)return{match:5,round:'Semi-final',a:resultPlayer(1),b:resultPlayer(2)}; if(no===6)return{match:6,round:'Semi-final',a:resultPlayer(3),b:resultPlayer(4)}; if(no===7)return{match:7,round:'Final',a:resultPlayer(5),b:resultPlayer(6)}} return null;}
  function nextMatch(){captureResult(); const size=Number(active().size||draft().size||state?.match?.tournamentSize||4), max=size===8?7:3, res=active().results||{}; for(let i=1;i<=max;i++){if(res[i])continue; const md=matchDef(i); if(md&&md.a&&md.b)return md;} return null;}
  function teamHtml(p, matchNo){const r=active().results&&active().results[matchNo]; const won=r&&((r.seed||r.winnerSeed)===(p&&p.seed)||String(r.name||r.winnerName).toLowerCase()===playerName(p).toLowerCase()); return '<div class="sq-bracket-team '+(p?'':'pending')+' '+(won?'winner':'')+'"><span class="sq-bracket-seed">'+esc(seedLabel(p))+'</span>'+esc(playerName(p))+'</div>';}
  function matchHtml(no){const md=matchDef(no)||{match:no,a:null,b:null,round:'TBC'}; return '<div class="sq-bracket-match"><div class="sq-bracket-match-title">'+esc(md.round||'Match '+no)+' · Match '+no+'</div>'+teamHtml(md.a,no)+teamHtml(md.b,no)+'</div>';}
  function winnerHtml(matchNo){const p=resultPlayer(matchNo);return '<div class="sq-bracket-winner-card"><div class="sq-bracket-match-title">Winner</div><div class="sq-bracket-cup">🏆</div><div class="sq-bracket-team '+(p?'winner':'pending')+'"><span class="sq-bracket-seed">'+esc(seedLabel(p))+'</span>'+esc(playerName(p))+'</div></div>';}
  function renderClassicTree(){const size=Number(active().size||draft().size||state?.match?.tournamentSize||4); if(size===8){return '<div class="sq-classic-bracket-wrap sq-ltr-bracket-wrap"><div class="sq-classic-bracket sq-ltr-bracket bracket8"><div class="sq-bracket-col sq-bracket-starts">'+matchHtml(1)+matchHtml(2)+matchHtml(3)+matchHtml(4)+'</div><div class="sq-bracket-col sq-bracket-semis">'+matchHtml(5)+matchHtml(6)+'</div><div class="sq-bracket-col sq-bracket-finals">'+matchHtml(7)+'</div><div class="sq-bracket-col sq-bracket-winner">'+winnerHtml(7)+'</div></div></div>';} return '<div class="sq-classic-bracket-wrap sq-ltr-bracket-wrap"><div class="sq-classic-bracket sq-ltr-bracket bracket4"><div class="sq-bracket-col sq-bracket-starts">'+matchHtml(1)+matchHtml(2)+'</div><div class="sq-bracket-col sq-bracket-finals">'+matchHtml(3)+'</div><div class="sq-bracket-col sq-bracket-winner">'+winnerHtml(3)+'</div></div></div>';}
  function toGamePlayer(sp){const name=playerName(sp),raw=sp&&sp.raw?sp.raw:{};let parts={first:name,last:''};try{if(typeof __sqNameParts==='function')parts=__sqNameParts(name)}catch(_){}let init=name.slice(0,2).toUpperCase();try{if(typeof __sqNormalizeInitials==='function')init=__sqNormalizeInitials(raw.initials||sp.initials,name)}catch(_){}return{type:raw.type||'registered',id:raw.id!=null?raw.id:(sp&&sp.id!=null?sp.id:null),name:name,first_name:String(raw.first_name||raw.first||sp.first_name||'').trim()||parts.first,last_name:String(raw.last_name||raw.last||sp.last_name||'').trim()||parts.last,nickname:String(raw.nickname||sp.nickname||'').trim(),initials:init,color:null,tournamentSeed:sp&&sp.seed,tournamentRank:sp&&sp.rank};}
  function startMatch(md){try{if(!md||!md.a||!md.b){try{toast('Next tournament match is not ready.')}catch(_){}return}const a=active(),d=draft();a.currentMatch=md.match;a.currentRound=md.round||'Tournament Match';state.__sqTournamentActive=a;state.__sqTournamentDraft=d;state.players=[toGamePlayer(md.a),toGamePlayer(md.b)];try{assignUniqueColors(state.players)}catch(_){}const id=typeof genUuidV4==='function'?genUuidV4():('tournament-'+Date.now());const rules=a.rules||d.rules||state?.match?.tournamentRules||{};state.match={id:id,mode:'official',tournament:true,tournamentType:a.type||d.type||state?.match?.tournamentType||'classic',tournamentSize:Number(a.size||d.size||state?.match?.tournamentSize||4),tournamentRound:md.round||'Tournament Match',tournamentMatch:md.match,tournamentRules:rules,forcePractice:false,practiceType:null,createdAtIso:new Date().toISOString(),targetWins:1,gameNumber:1,wins:[0,0],history:[],completedLogged:false};state.matchAgg=null;state.finished=false;state.gameAwarded=false;state.currentRound=0;state.currentPlayer=0;state.currentDart=0;state.history=[];state.score=[];try{ensureMatchAgg()}catch(_){}try{save()}catch(_){}try{startNewGame(false)}catch(e){console.error('[SQ] Fix83 start match failed',e);}}catch(e){console.error('[SQ] Fix83 start match failed',e)}}
  function openTree(){captureResult();const next=nextMatch();const ov=document.createElement('div');ov.className='modal-backdrop sq-tournament-tree-modal';const md=document.createElement('div');md.className='modal';md.style.maxWidth='980px';const body=document.createElement('div');body.className='modal-body';body.innerHTML='<div class="sg-tournament-intro"><div class="sg-tournament-title">UPDATED KNOCKOUT TREE</div><div class="sg-tournament-sub">Bracket progresses left to right from starting matches to the winner.</div></div>'+renderClassicTree();const ft=document.createElement('div');ft.className='modal-footer';const nxt=document.createElement('button');nxt.className='btn primary';nxt.textContent=next?'Next':'Tournament Complete';nxt.disabled=!next;nxt.onclick=function(){if(next){ov.remove();startMatch(next)}};ft.append(nxt);md.append(body,ft);ov.appendChild(md);document.body.appendChild(ov);md.tabIndex=0;md.focus();ov.addEventListener('click',e=>{if(e.target===ov)ov.remove()});}
  function patchLeaderboard(){try{if(!isLeaderboard()||!isTournament()||!matchDone())return false; captureResult(); const stack=document.querySelector('#leaderboard .stacked-actions')||document.querySelector('.stacked-actions'); if(!stack)return false; Array.from(stack.querySelectorAll('button')).forEach(b=>{const t=txt(b); if(t==='HIGH SCORES'||t==='PREMIER LEAGUE'||b.id==='sqTournamentNextRoundBtn'||b.id==='sqTournamentNextRoundBtnFix81'||b.id==='sqTournamentNextRoundBtnFix82'){b.style.display='none';b.classList.add('hidden','sqTournamentHideBtn');}}); let next=document.getElementById('sqTournamentNextRoundBtnFix83'); if(!next){next=document.createElement('button');next.id='sqTournamentNextRoundBtnFix83';next.type='button';next.className='btn primary big';next.textContent='NEXT ROUND';}next.onclick=function(e){e.preventDefault();openTree();}; const gameScores=Array.from(stack.querySelectorAll('button')).find(b=>txt(b)==='GAME SCORES'); const end=document.getElementById('newMatchBtn')||Array.from(stack.querySelectorAll('button')).find(b=>txt(b)==='END MATCH'); let gap=document.getElementById('sqFix83TournamentGap'); if(!gap){gap=document.createElement('div');gap.id='sqFix83TournamentGap';} stack.appendChild(next); stack.appendChild(gap); if(gameScores)stack.appendChild(gameScores); if(end)stack.appendChild(end); return true;}catch(e){console.warn('[SQ] Fix83 leaderboard patch failed',e);return false;}}
  window.__sqOpenTournamentTreeFromLeaderboard=openTree;
  window.__sqFix83PatchTournamentLeaderboardNow=patchLeaderboard;
  window.__sqFix83TournamentDebug=function(){return{page:document.body?.dataset?.page,isTournament:isTournament(),matchDone:matchDone(),active:active(),draft:draft(),next:nextMatch(),patched:patchLeaderboard()};};
  setInterval(patchLeaderboard,250);
  setTimeout(patchLeaderboard,0);setTimeout(patchLeaderboard,250);setTimeout(patchLeaderboard,1000);
  document.addEventListener('click',function(e){try{const btn=e.target&&e.target.closest?e.target.closest('button'):null;if(!btn)return;const t=txt(btn);if(t.indexOf('MISS X')===0||t.replace(/\s+/g,'').indexOf('MISSX3')>=0||btn.classList.contains('dtX3')){const before=String((state?.currentRound||0)+'/'+(state?.currentPlayer||0)+'/'+(state?.currentDart||0)+'/'+JSON.stringify(state?.score||[]).length);setTimeout(function(){try{const after=String((state?.currentRound||0)+'/'+(state?.currentPlayer||0)+'/'+(state?.currentDart||0)+'/'+JSON.stringify(state?.score||[]).length);if(after===before&&typeof pressMissN==='function'){pressMissN(3);}}catch(_){}},120);}}catch(_){}},true);
})();
